---
version: "2"
linters:
  enable:
    - bodyclose
    - forbidigo
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - (io.ReadCloser).Close
      verbose: true
formatters:
  enable:
    - gofumpt
